### ISSUE TITLE
Bug/Missing timezone information

### ISSUE THREAD

**Issue by Luktronic** [Ardas-Legends-Development-Team/Ardas-Legends-App#132]
**Describe the bug**
Currently all Dates are stored as `LocalDateTime`, which leads to problems when we are trying to display dates to our users in the frontend. The backend server stores the timestamps in its local timezone, and does not convert them to UTC time with timezone information.

**Expected behavior**
The backend should store all Dates as `OffsetDateTime`, which leads to this representation: `2007-12-03T10:15:30+01:00`. This is the UTC representation, including the timezone information in the end. This way we can convert the timestamps to the end user's local time, showing them localized time values in the frontend (for example estimated movement completion time being shown in the user's local time instead of UTC).

**Screenshots**
Use of `OffsetDateTime` instead of `LocalDateTime`
![image](https://github.com/Ardas-Legends-Development-Team/Ardas-Legends-App/assets/59698507/f2147588-5342-4f7f-b289-f8affbf2703c)

**Additional context**
We could write a converter which simply converts all the `LocalDateTime`s to `OffsetDateTime`s when sending responses, but this would lead to problems if we ever host the database on another server that is in a different timezone than the current one. It could also lead to other unexpected behaviour, so we decided to just redo it from the ground up in order to avoid any errors in the future.

**ToDo**
- [x] Switch to `OffsetDateTime` in `Army`
- [x] Switch to `OffsetDateTime` in `Movement`
- [x] Switch to `OffsetDateTime` in `RPChar`
- [x] Switch to `OffsetDateTime` in `AbstractApplication`
- [x] Switch to `OffsetDateTime` in `Battle`
- [x] Switch to `OffsetDateTime` in `War`
- [x] Switch to `OffsetDateTime` in all api Response classes
